TARA_WEIGHT = 100
GRAMS_PER_SENSOR_UNIT = 10
UNIT_PRECISION = 3;

GRAMS_PER_FEEDING_PER_PET = 20
PET_COUNT = 2
GRAMS_PER_FEEDING = GRAMS_PER_FEEDING_PER_PET * PET_COUNT
FEEDING_INTERVAL_HOURS = 24
ALERT_LEVEL_GRAMS = GRAMS_PER_FEEDING_PER_PET * PET_COUNT * FEEDING_INTERVAL_HOURS / 12
ALERT_LEVEL_SENSOR_UNIT = TARA_WEIGHT  + ALERT_LEVEL_GRAMS / GRAMS_PER_SENSOR_UNIT

SCRIPT_INTERVAL_SECONDS = 600